version: '3.3'

services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    ports:
      - '8080:8080'
    environment:
      - JWT_SECRET=307a11e7180b3728fea818da402762cdf58e69a6d53c99a0a7c0edf27c8a3b83

  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: uix23wr
  
  redis:
    image: redis:3.2.11
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB_NUMBER=0