version: '3.3'

services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    ports:
      - '8080:8080'

  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: uix23wr