version: '3.3'

services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - .:/go/src/github.com/defraglabs/uptime
    environment:
      - ENV=local
      - JWT_SECRET=307a11e7180b3728fea818da402762cdf58e69a6d53c99a0a7c0edf27c8a3b83
      - MONGO_HOST=db
      - MONGO_DATABASE_NAME=uptime
      - MONGO_INITDB_ROOT_PASSWORD=uix23wr
      - FROM_EMAIL=support@uptime.com
      - FORGOT_PASSWORD_LINK=reset-password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB_NUMBER=0

  db:
    image: mongo
    volumes:
      - dbdata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: uix23wr
  
  redis:
    image: redis:3.2.11
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB_NUMBER=0
  
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  dbdata:
    driver: local
